### ISSUE TITLE
Sub menus not accessible with keyboard

### ISSUE THREAD

**Issue by phun-ky** [NickDJM/accessible-menu#208] opened 2023-03-28 07:10 UTC
## Summary
Sub menus not accessible with keyboard

## Steps to reproduce
1. Use accessible menu with Disclosure menu
2. Make sure you have sub menus
3. Try to navigate to Company -> Statistics -> Experience with keyboard

## Expected Behaviour
Sub menus are reachable with keyboard navigation

## Info

<details>
<summary>
HTML
</summary>

```html
<ul aria-labelledby="example-toggle" class="hide" id="toggle-example-menu-xjqfnzybv-menu">
        <li class="ki is-parent">
          <button aria-controls="me-cerqqkcskb-menu" aria-expanded="false" aria-haspopup="true" class="ki action" id="me-cerqqkcskb-menu-button" type="button">Me</button>
          <ul aria-labelledby="me-cerqqkcskb-menu-button" class="ki hide" id="me-cerqqkcskb-menu">
            <li class="ki">
              <a class="ki ki action" data-link="/employees/me" href="/employees/me" id="">My profile</a>
            </li>
            <li class="ki">
              <a class="ki ki action" href="/auth/logout" id="logout">Log out</a>
            </li>
          </ul>
        </li>
        <li class="ki is-parent">
          <button aria-controls="company-nzfeoiet-menu" aria-expanded="true" aria-haspopup="true" class="ki action" id="company-nzfeoiet-menu-button" type="button">Company</button>
          <ul aria-labelledby="company-nzfeoiet-menu-button" class="ki show" id="company-nzfeoiet-menu">
            <li class="ki">
              <a class="ki ki action" data-link="/employees" href="/employees" id="">Employees</a>
            </li>
            <li class="ki">
              <a class="ki ki action" href="https://folk.domain.com" id="" rel="noopener noreferrer" target="_blank">Employees (old folk) (opens in new window)</a>
            </li>
            <li class="ki is-parent">
              <a aria-controls="statistics-ssjqozcs-menu" aria-expanded="false" aria-haspopup="true" class="ki ki action" data-link="/statistics" href="/statistics" id="statistics-ssjqozcs-menu-button" role="button">Statistics</a>
              <ul aria-labelledby="statistics-ssjqozcs-menu-button" class="ki hide" id="statistics-ssjqozcs-menu">
                <li class="ki">
                  <a class="ki ki action" data-link="/statistics/experience" href="/statistics/experience" id="">Experience</a>
                </li>
              </ul>
            </li>
            <li class="ki">
              <a class="ki ki action" data-link="/staffing" href="/staffing" id="">Staffing</a>
            </li>
          </ul>
        </li>
        <li class="ki is-parent">
          <button aria-controls="competence-shzozocd-menu" aria-expanded="false" aria-haspopup="true" class="ki action" id="competence-shzozocd-menu-button" type="button">Competence</button>
          <ul aria-labelledby="competence-shzozocd-menu-button" class="ki hide" id="competence-shzozocd-menu">
            <li class="ki">
              <a class="ki ki action" href="https://kompetanse.domain.com" id="" rel="noopener noreferrer" target="_blank">Competence mapping (opens in new window)</a>
            </li>
          </ul>
        </li>
        <li class="ki is-parent">
          <button aria-controls="resources-jcbqpw-menu" aria-expanded="false" aria-haspopup="true" class="ki action" id="resources-jcbqpw-menu-button" type="button">Resources</button>
          <ul aria-labelledby="resources-jcbqpw-menu-button" class="ki hide" id="resources-jcbqpw-menu">
            <li class="ki">
              <a class="ki ki action" href="https://domain.cvpartner.dk" id="" rel="noopener noreferrer" target="_blank">CVPartner (opens in new window)</a>
            </li>
            <li class="ki">
              <a class="ki ki action" href="https://epost.domain.com" id="" rel="noopener noreferrer" target="_blank">Email (opens in new window)</a>
            </li>
            <li class="ki">
              <a class="ki ki action" href="https://domain.slack.com" id="" rel="noopener noreferrer" target="_blank">Slack (opens in new window)</a>
            </li>
            <li class="ki">
              <a class="ki ki action" href="https://timer.domain.com" id="" rel="noopener noreferrer" target="_blank">Timekeeping (opens in new window)</a>
            </li>
            <li class="ki">
              <a class="ki ki action" href="https://kalender.domain.com" id="" rel="noopener noreferrer" target="_blank">Calendar (opens in new window)</a>
            </li>
            <li class="ki">
              <a class="ki ki action" href="https://domain.unit4cloud.dk" id="" rel="noopener noreferrer" target="_blank">Expenses (opens in new window)</a>
            </li>
            <li class="ki">
              <a class="ki ki action" href="https://helpit.domain.com" id="" rel="noopener noreferrer" target="_blank">HelpIt (opens in new window)</a>
            </li>
            <li class="ki">
              <a class="ki ki action" href="https://sharepoint.domain.com" id="" rel="noopener noreferrer" target="_blank">Sharepoint (opens in new window)</a>
            </li>
          </ul>
        </li>
      </ul>
```

</details>

**Comment by NickDJM** [comment] 2023-03-30 16:41
@phun-ky can you also post the JS you're using to initialize accessible-menu?

**Comment by NickDJM** [comment] 2023-05-19 15:33
@phun-ky Just wanted to ping this again.

- Are you able to provide the JS you're initializing accessible-menu with?
- Are you using the optionalKeySupport flag?
- When you say "keyboard navigation" are you talking about tabbing, arrow keys, both?

**Comment by NickDJM** [comment] 2023-06-22 15:14
Closing.

Cannot reproduce and no additional information has been provided.

**Closed as completed by NickDJM** 2023-06-22 15:14 UTC
Labels: bug
